export const datosOdontologia:string[] = [
  "¿Sabías que un cepillo de dientes típico contiene alrededor de 2,500 cerdas agrupadas en 40 penachos?",
  "El esmalte dental es la sustancia más dura del cuerpo humano. ¡Es incluso más duro que los huesos!",
  "A lo largo de su vida, una persona produce aproximadamente 25,000 litros de saliva. ¡Es suficiente para llenar dos piscinas!",
  "El hilo dental es la única herramienta que puede eliminar la placa entre los dientes. ¡Cepillarse solo limpia el 60% de la superficie!",
  "Los antiguos romanos usaban una mezcla de orina para blanquear sus dientes. ¡No te preocupes, la pasta de dientes moderna es mucho mejor!",
  "Una muela del juicio recibe su nombre porque generalmente aparece entre los 17 y 25 años, una edad de mayor 'sabiduría'.",
  "El primer dentista conocido en la historia fue Hesi-Re, un escriba egipcio que vivió hace más de 4,000 años.",
  "El dolor de muelas se reportó por primera vez hace 5,000 años en un texto sumerio.",
  "El cepillo de dientes de cerdas suaves es el más recomendado por los dentistas para evitar dañar el esmalte y las encías.",
  "Las enfermedades de las encías están relacionadas con problemas cardíacos, diabetes y derrames cerebrales.",
  "Los humanos tienen dos juegos de dientes en su vida: los dientes de leche y los permanentes. ¡Los tiburones tienen hasta 40!",
  "Los dientes son tan únicos como las huellas dactilares. ¡Nadie más tiene tus mismos dientes!",
  "Los dentistas recomiendan cambiar tu cepillo de dientes cada 3 o 4 meses, o antes si las cerdas están desgastadas.",
  "La saliva ayuda a proteger nuestros dientes de las bacterias al neutralizar los ácidos y remineralizar el esmalte.",
  "Los primeros cepillos de dientes se inventaron en China en el siglo XV y usaban cerdas de jabalí.",
  "El 78% de los americanos se cepillan la lengua para evitar el mal aliento.",
  "El uso del palillo de dientes es una de las prácticas dentales más antiguas, con evidencia que se remonta a la prehistoria.",
  "Un diente de leche tiene un 5% de probabilidades de convertirse en un diente de tiburón. ¡Es broma! Pero sería genial, ¿verdad?",
  "La enfermedad periodontal (de las encías) es la segunda enfermedad más común del mundo, después del resfriado.",
  "Se necesitan 17 músculos para sonreír y 43 para fruncir el ceño. ¡Sonreír es más fácil y más beneficioso!",
  "El primer cepillo de dientes eléctrico fue inventado en Suiza en 1954.",
  "Más de 300 tipos de bacterias viven en tu boca. ¡No te preocupes, la mayoría son inofensivas si mantienes una buena higiene!",
  "El diente más caro de la historia perteneció a Sir Isaac Newton, y se vendió por $3,633 en 1816.",
  "Una de cada 2,000 personas nace con un diente. Se les llama 'dientes natales'.",
  "A los 17 años, alrededor del 7.3% de los jóvenes tienen al menos una cavidad no tratada.",
  "El esmalte dental es la única parte del cuerpo humano que no puede regenerarse por sí misma.",
  "La persona promedio gasta 38.5 días de su vida cepillándose los dientes.",
  "Los dentistas han estado usando radiografías desde 1896, justo un año después de su descubrimiento.",
  "El 25% de los adultos mayores de 60 años ha perdido todos sus dientes.",
  "Las jirafas solo tienen dientes en la parte inferior de la boca.",
  "La sonrisa es la primera cosa que la gente nota en una persona. ¡Una buena razón para cuidar tus dientes!",
  "Los dientes de la Reina Isabel I eran negros debido a su adicción al azúcar.",
  "Un elefante tiene seis juegos de molares a lo largo de su vida. Cuando un juego se desgasta, es reemplazado por otro.",
  "El primer taladro dental fue accionado con el pie, como una máquina de coser.",
  "La antigua pasta de dientes egipcia estaba hecha de ceniza, piedra pómez y vinagre. ¡Agradece la menta!",
  "Las enfermedades de las encías son 300 veces más probables de causar complicaciones en el embarazo que la edad avanzada.",
  "La boca es el lugar más supepoblado de bacterias, con alrededor de 20 mil millones de microorganismos.",
  "Los dientes permanentes comienzan a formarse justo al nacer, debajo de las encías.",
  "El ratón de los dientes es un mito. En Francia, los dientes de leche los recoge un pequeño ratón llamado 'La Petite Souris'.",
  "Las enfermedades de las encías se han relacionado con la osteoporosis y la artritis reumatoide.",
  "El hilo dental se inventó en 1815, pero no se produjo en masa hasta la Segunda Guerra Mundial.",
  "Los dientes son las partes del cuerpo humano que mejor se conservan en un fósil.",
  "Los monos son los únicos animales que tienen la misma cantidad de dientes que los humanos.",
  "El 70% de las personas prefieren una sonrisa perfecta antes que un físico perfecto.",
  "El término 'odontología' proviene de la palabra griega 'odous', que significa diente."
];